### ISSUE TITLE
numpy.linalg.LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by theoldnewb** [marmakoide/miniball#3]
Hello marmakoide,

Sadly, the first 3D point cloud that I tested miniball with, failed with a singular matrix error.
In case you are wondering, the point cloud is just the vertex positions of the default Suzanne Blender model with a subdivision surface modifier applied.
I attached a little reproducer named 'test_miniball.py'

Kind regards,
theoldnewb

Traceback (most recent call last):
  File "/home...src/./test_miniball.py", line 3055, in <module>
    C, r2 = miniball.get_bounding_ball(arr)
  File "/home...lib/python3.9/site-packages/miniball.py", line 127, in get_bounding_ball
    traverse(root)
  File "/home...lib/python3.9/site-packages/miniball.py", line 110, in traverse
    node.D = get_boundary(node.R)
  File "/home...lib/python3.9/site-packages/miniball.py", line 89, in get_boundary
    return get_circumsphere(S[R])
  File "/home...lib/python3.9/site-packages/miniball.py", line 48, in get_circumsphere
    C = numpy.dot(numpy.linalg.solve(numpy.inner(U, U), B), U)
  File "<__array_function__ internals>", line 5, in solve
  File "/home...lib/python3.9/site-packages/numpy/linalg/linalg.py", line 393, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home...lib/python3.9/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

[test_miniball.py.txt](https://github.com/marmakoide/miniball/files/7099899/test_miniball.py.txt)

**Comment by marmakoide** [comment]
I ran your test script, and I was available to find the origin of the crash : your input point list contains duplicates.

As a quick workaround, you should remove those duplicates yourself, using numpy.unique. I will push an updated version of miniball to handle this case in a few days. Thank you very much to report this issue !

**Comment by theoldnewb** [comment]
Thank you very much for the investigation. The data with numpy.unique worked great. Now I feel somewhat stupid that I haven't considered that duplicates might be a problem. Thank you again. This is really useful neat code to precalc bounding spheres. Thank you for making it.
